//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursa
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Банк дан.
    /// </summary>
    // *** Start programmer edit section *** (БанкДан CustomAttributes)

    // *** End programmer edit section *** (БанкДан CustomAttributes)
    [AutoAltered()]
    [Caption("Банк дан")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БанкДанE", new string[] {
            "НомКарт as \'Номер карты\'",
            "CVV as \'CVV\'",
            "Дата as \'Дата окончания\'"})]
    [View("БанкДанL", new string[] {
            "НомКарт as \'Номер карты\'",
            "CVV as \'CVV\'",
            "Дата as \'Дата окончания\'"})]
    public class БанкДан : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомКарт;
        
        private int fCVV;
        
        private string fДата;
        
        // *** Start programmer edit section *** (БанкДан CustomMembers)

        // *** End programmer edit section *** (БанкДан CustomMembers)

        
        /// <summary>
        /// CVV.
        /// </summary>
        // *** Start programmer edit section *** (БанкДан.CVV CustomAttributes)

        // *** End programmer edit section *** (БанкДан.CVV CustomAttributes)
        public virtual int CVV
        {
            get
            {
                // *** Start programmer edit section *** (БанкДан.CVV Get start)

                // *** End programmer edit section *** (БанкДан.CVV Get start)
                int result = this.fCVV;
                // *** Start programmer edit section *** (БанкДан.CVV Get end)

                // *** End programmer edit section *** (БанкДан.CVV Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БанкДан.CVV Set start)

                // *** End programmer edit section *** (БанкДан.CVV Set start)
                this.fCVV = value;
                // *** Start programmer edit section *** (БанкДан.CVV Set end)

                // *** End programmer edit section *** (БанкДан.CVV Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (БанкДан.Дата CustomAttributes)

        // *** End programmer edit section *** (БанкДан.Дата CustomAttributes)
        [StrLen(255)]
        public virtual string Дата
        {
            get
            {
                // *** Start programmer edit section *** (БанкДан.Дата Get start)

                // *** End programmer edit section *** (БанкДан.Дата Get start)
                string result = this.fДата;
                // *** Start programmer edit section *** (БанкДан.Дата Get end)

                // *** End programmer edit section *** (БанкДан.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БанкДан.Дата Set start)

                // *** End programmer edit section *** (БанкДан.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (БанкДан.Дата Set end)

                // *** End programmer edit section *** (БанкДан.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомКарт.
        /// </summary>
        // *** Start programmer edit section *** (БанкДан.НомКарт CustomAttributes)

        // *** End programmer edit section *** (БанкДан.НомКарт CustomAttributes)
        [StrLen(255)]
        public virtual string НомКарт
        {
            get
            {
                // *** Start programmer edit section *** (БанкДан.НомКарт Get start)

                // *** End programmer edit section *** (БанкДан.НомКарт Get start)
                string result = this.fНомКарт;
                // *** Start programmer edit section *** (БанкДан.НомКарт Get end)

                // *** End programmer edit section *** (БанкДан.НомКарт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БанкДан.НомКарт Set start)

                // *** End programmer edit section *** (БанкДан.НомКарт Set start)
                this.fНомКарт = value;
                // *** Start programmer edit section *** (БанкДан.НомКарт Set end)

                // *** End programmer edit section *** (БанкДан.НомКарт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БанкДанE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БанкДанE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БанкДанE", typeof(IIS.Kursa.БанкДан));
                }
            }
            
            /// <summary>
            /// "БанкДанL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БанкДанL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БанкДанL", typeof(IIS.Kursa.БанкДан));
                }
            }
        }
    }
}
