//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursa
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заправ бак.
    /// </summary>
    // *** Start programmer edit section *** (ЗаправБак CustomAttributes)

    // *** End programmer edit section *** (ЗаправБак CustomAttributes)
    [AutoAltered()]
    [Caption("Заправ бак")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаправБакE", new string[] {
            "ТипТопл as \'Тип топлива\'",
            "Цена as \'Цена\'",
            "УровЗалив as \'Уровень заливки\'",
            "Объем as \'Объем\'",
            "Техсост as \'Техническое состояние\'"})]
    [View("ЗаправБакL", new string[] {
            "ТипТопл as \'Тип топлива\'",
            "Цена as \'Цена\'",
            "Объем as \'Объем\'",
            "УровЗалив as \'Уровень заливки\'",
            "Техсост as \'Техническое состояние\'"})]
    public class ЗаправБак : ICSSoft.STORMNET.DataObject
    {
        
        private string fТипТопл;
        
        private float fЦена;
        
        private int fОбъем;
        
        private int fУровЗалив;
        
        private bool fТехсост;
        
        // *** Start programmer edit section *** (ЗаправБак CustomMembers)

        // *** End programmer edit section *** (ЗаправБак CustomMembers)

        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.Объем CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.Объем CustomAttributes)
        public virtual int Объем
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.Объем Get start)

                // *** End programmer edit section *** (ЗаправБак.Объем Get start)
                int result = this.fОбъем;
                // *** Start programmer edit section *** (ЗаправБак.Объем Get end)

                // *** End programmer edit section *** (ЗаправБак.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.Объем Set start)

                // *** End programmer edit section *** (ЗаправБак.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (ЗаправБак.Объем Set end)

                // *** End programmer edit section *** (ЗаправБак.Объем Set end)
            }
        }
        
        /// <summary>
        /// Техсост.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.Техсост CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.Техсост CustomAttributes)
        public virtual bool Техсост
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.Техсост Get start)

                // *** End programmer edit section *** (ЗаправБак.Техсост Get start)
                bool result = this.fТехсост;
                // *** Start programmer edit section *** (ЗаправБак.Техсост Get end)

                // *** End programmer edit section *** (ЗаправБак.Техсост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.Техсост Set start)

                // *** End programmer edit section *** (ЗаправБак.Техсост Set start)
                this.fТехсост = value;
                // *** Start programmer edit section *** (ЗаправБак.Техсост Set end)

                // *** End programmer edit section *** (ЗаправБак.Техсост Set end)
            }
        }
        
        /// <summary>
        /// ТипТопл.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.ТипТопл CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.ТипТопл CustomAttributes)
        [StrLen(255)]
        public virtual string ТипТопл
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.ТипТопл Get start)

                // *** End programmer edit section *** (ЗаправБак.ТипТопл Get start)
                string result = this.fТипТопл;
                // *** Start programmer edit section *** (ЗаправБак.ТипТопл Get end)

                // *** End programmer edit section *** (ЗаправБак.ТипТопл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.ТипТопл Set start)

                // *** End programmer edit section *** (ЗаправБак.ТипТопл Set start)
                this.fТипТопл = value;
                // *** Start programmer edit section *** (ЗаправБак.ТипТопл Set end)

                // *** End programmer edit section *** (ЗаправБак.ТипТопл Set end)
            }
        }
        
        /// <summary>
        /// УровЗалив.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.УровЗалив CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.УровЗалив CustomAttributes)
        public virtual int УровЗалив
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.УровЗалив Get start)

                // *** End programmer edit section *** (ЗаправБак.УровЗалив Get start)
                int result = this.fУровЗалив;
                // *** Start programmer edit section *** (ЗаправБак.УровЗалив Get end)

                // *** End programmer edit section *** (ЗаправБак.УровЗалив Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.УровЗалив Set start)

                // *** End programmer edit section *** (ЗаправБак.УровЗалив Set start)
                this.fУровЗалив = value;
                // *** Start programmer edit section *** (ЗаправБак.УровЗалив Set end)

                // *** End programmer edit section *** (ЗаправБак.УровЗалив Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.Цена CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.Цена CustomAttributes)
        public virtual float Цена
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.Цена Get start)

                // *** End programmer edit section *** (ЗаправБак.Цена Get start)
                float result = this.fЦена;
                // *** Start programmer edit section *** (ЗаправБак.Цена Get end)

                // *** End programmer edit section *** (ЗаправБак.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.Цена Set start)

                // *** End programmer edit section *** (ЗаправБак.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ЗаправБак.Цена Set end)

                // *** End programmer edit section *** (ЗаправБак.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаправБакE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаправБакE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаправБакE", typeof(IIS.Kursa.ЗаправБак));
                }
            }
            
            /// <summary>
            /// "ЗаправБакL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаправБакL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаправБакL", typeof(IIS.Kursa.ЗаправБак));
                }
            }
        }
    }
}
