//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursa
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Карта лояль.
    /// </summary>
    // *** Start programmer edit section *** (КартаЛояль CustomAttributes)

    // *** End programmer edit section *** (КартаЛояль CustomAttributes)
    [AutoAltered()]
    [Caption("Карта лояльности")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КартаЛояльE", new string[] {
            "Ном as \'Номер\'",
            "ПроцСкид as \'Процент скидки\'",
            "СуммПокуп as \'Сумма покупок\'"})]
    [View("КартаЛояльL", new string[] {
            "Ном as \'Номер\'",
            "СуммПокуп as \'Сумма покупок\'",
            "ПроцСкид as \'Процент скидки\'"})]
    public class КартаЛояль : ICSSoft.STORMNET.DataObject
    {
        
        private int fНом;
        
        private float fПроцСкид;
        
        private float fСуммПокуп;
        
        // *** Start programmer edit section *** (КартаЛояль CustomMembers)

        // *** End programmer edit section *** (КартаЛояль CustomMembers)

        
        /// <summary>
        /// Ном.
        /// </summary>
        // *** Start programmer edit section *** (КартаЛояль.Ном CustomAttributes)

        // *** End programmer edit section *** (КартаЛояль.Ном CustomAttributes)
        public virtual int Ном
        {
            get
            {
                // *** Start programmer edit section *** (КартаЛояль.Ном Get start)

                // *** End programmer edit section *** (КартаЛояль.Ном Get start)
                int result = this.fНом;
                // *** Start programmer edit section *** (КартаЛояль.Ном Get end)

                // *** End programmer edit section *** (КартаЛояль.Ном Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартаЛояль.Ном Set start)

                // *** End programmer edit section *** (КартаЛояль.Ном Set start)
                this.fНом = value;
                // *** Start programmer edit section *** (КартаЛояль.Ном Set end)

                // *** End programmer edit section *** (КартаЛояль.Ном Set end)
            }
        }
        
        /// <summary>
        /// ПроцСкид.
        /// </summary>
        // *** Start programmer edit section *** (КартаЛояль.ПроцСкид CustomAttributes)

        // *** End programmer edit section *** (КартаЛояль.ПроцСкид CustomAttributes)
        public virtual float ПроцСкид
        {
            get
            {
                // *** Start programmer edit section *** (КартаЛояль.ПроцСкид Get start)

                // *** End programmer edit section *** (КартаЛояль.ПроцСкид Get start)
                float result = this.fПроцСкид;
                // *** Start programmer edit section *** (КартаЛояль.ПроцСкид Get end)

                // *** End programmer edit section *** (КартаЛояль.ПроцСкид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартаЛояль.ПроцСкид Set start)

                // *** End programmer edit section *** (КартаЛояль.ПроцСкид Set start)
                this.fПроцСкид = value;
                // *** Start programmer edit section *** (КартаЛояль.ПроцСкид Set end)

                // *** End programmer edit section *** (КартаЛояль.ПроцСкид Set end)
            }
        }
        
        /// <summary>
        /// СуммПокуп.
        /// </summary>
        // *** Start programmer edit section *** (КартаЛояль.СуммПокуп CustomAttributes)

        // *** End programmer edit section *** (КартаЛояль.СуммПокуп CustomAttributes)
        public virtual float СуммПокуп
        {
            get
            {
                // *** Start programmer edit section *** (КартаЛояль.СуммПокуп Get start)

                // *** End programmer edit section *** (КартаЛояль.СуммПокуп Get start)
                float result = this.fСуммПокуп;
                // *** Start programmer edit section *** (КартаЛояль.СуммПокуп Get end)

                // *** End programmer edit section *** (КартаЛояль.СуммПокуп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартаЛояль.СуммПокуп Set start)

                // *** End programmer edit section *** (КартаЛояль.СуммПокуп Set start)
                this.fСуммПокуп = value;
                // *** Start programmer edit section *** (КартаЛояль.СуммПокуп Set end)

                // *** End programmer edit section *** (КартаЛояль.СуммПокуп Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КартаЛояльE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартаЛояльE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартаЛояльE", typeof(IIS.Kursa.КартаЛояль));
                }
            }
            
            /// <summary>
            /// "КартаЛояльL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартаЛояльL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартаЛояльL", typeof(IIS.Kursa.КартаЛояль));
                }
            }
        }
    }
}
