//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursa
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товары спр.
    /// </summary>
    // *** Start programmer edit section *** (ТоварыСпр CustomAttributes)

    // *** End programmer edit section *** (ТоварыСпр CustomAttributes)
    [AutoAltered()]
    [Caption("Товары спр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварыСпрE", new string[] {
            "Наим as \'Наименование\'",
            "Цена as \'Цена\'"})]
    [View("ТоварыСпрL", new string[] {
            "Наим as \'Наименование\'",
            "Цена as \'Цена\'"})]
    public class ТоварыСпр : ICSSoft.STORMNET.DataObject
    {
        
        private float fЦена;
        
        private string fНаим;
        
        // *** Start programmer edit section *** (ТоварыСпр CustomMembers)

        // *** End programmer edit section *** (ТоварыСпр CustomMembers)

        
        /// <summary>
        /// Наим.
        /// </summary>
        // *** Start programmer edit section *** (ТоварыСпр.Наим CustomAttributes)

        // *** End programmer edit section *** (ТоварыСпр.Наим CustomAttributes)
        [StrLen(255)]
        public virtual string Наим
        {
            get
            {
                // *** Start programmer edit section *** (ТоварыСпр.Наим Get start)

                // *** End programmer edit section *** (ТоварыСпр.Наим Get start)
                string result = this.fНаим;
                // *** Start programmer edit section *** (ТоварыСпр.Наим Get end)

                // *** End programmer edit section *** (ТоварыСпр.Наим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварыСпр.Наим Set start)

                // *** End programmer edit section *** (ТоварыСпр.Наим Set start)
                this.fНаим = value;
                // *** Start programmer edit section *** (ТоварыСпр.Наим Set end)

                // *** End programmer edit section *** (ТоварыСпр.Наим Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ТоварыСпр.Цена CustomAttributes)

        // *** End programmer edit section *** (ТоварыСпр.Цена CustomAttributes)
        public virtual float Цена
        {
            get
            {
                // *** Start programmer edit section *** (ТоварыСпр.Цена Get start)

                // *** End programmer edit section *** (ТоварыСпр.Цена Get start)
                float result = this.fЦена;
                // *** Start programmer edit section *** (ТоварыСпр.Цена Get end)

                // *** End programmer edit section *** (ТоварыСпр.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварыСпр.Цена Set start)

                // *** End programmer edit section *** (ТоварыСпр.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ТоварыСпр.Цена Set end)

                // *** End programmer edit section *** (ТоварыСпр.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварыСпрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварыСпрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварыСпрE", typeof(IIS.Kursa.ТоварыСпр));
                }
            }
            
            /// <summary>
            /// "ТоварыСпрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварыСпрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварыСпрL", typeof(IIS.Kursa.ТоварыСпр));
                }
            }
        }
    }
}
